name: Release and Deploy Documentation

on:
  push:
    tags:
      - "*.*.*"
  # Allows manual trigger for documentation update
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: poetry run pytest

      - name: Build binary
        run: |
          pip install pyinstaller
          pyinstaller --onefile src/kendall_simulator/simulator.py --name kendall-simulator

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: kendall-simulator-${{ runner.os }}
          path: dist/kendall-simulator*

  create_release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Generate Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            kendall-simulator-Linux/*
            kendall-simulator-Windows/*
            kendall-simulator-macOS/*

  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Sphinx docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy_docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: Deployment
        uses: sphinx-notes/pages@v3
        with:
          python_version: "3.13"
          checkout: false
